### ISSUE TITLE
Create NFT Anchor program 

### ISSUE THREAD

**Issue by 0xPratik** [solana-developers/program-examples#1]
Hey @jpcaulfi i would love to put this example here. I have a repo which has an example of this but it seams it needs to be updated as its 5 months old. https://github.com/0xPratik/NFT/blob/master/programs/mpl-testing/src/lib.rs

**Comment by jpcaulfi** [comment]
Awesome! Just add some comments and maybe use Anchor's ’CpiContext’ instead of ’invoke’ and submit a PR!   
You can add it to the ’mint-2’ example with an associated test.

**Comment by 0xPratik** [comment]
Cool i will add it soon

**Comment by ngundotra** [comment]
Would love to see this! @0xPratik
