### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by dadepo** [solana-developers/program-examples#11]
It would be nice to have a setup where the example programs can be deployed and the client tests ran against them. I think it should be possible to set this up with github actions. 

If this is considered worth having, then I will be happy to help setup.

**Comment by realbuffalojoe** [comment]
this is a really cool idea - jw how you'd implement it in the repo?

For example, if GitHub actions will deploy each program and assign each one it's own ProgramID, how do I target that ProgramID when I clone this thing down and run tests?

**Comment by realbuffalojoe** [comment]
You could have like a `tests/const.ts` file with the ID and then have a commented out line in each test for using that programID, as one idea
