### ISSUE TITLE
cannot index into a value of type `&mut Rc<RefCell<&mut [u8]>>`

### ISSUE THREAD

**Issue by krishhh16** [solana-developers/program-examples#162]
Getting this error in the  account_data native example

 when I write
     address_info.serialize(&mut &mut address_info_account.data.borrow_mut()[..])?;
in the create.rs file in the instructions folder
![image](https://github.com/user-attachments/assets/35090721-fa64-432c-b46f-b6e3ef22ec03)
This is the error that I get, while the same doesn't happen in the actual repository

Would appreciate help

**Comment by Hamissou227** [comment]
@krishhh16

**Comment by FlavioAcri** [comment]
Get the same error! Following the discussion.

**Comment by heyAyushh** [comment]
Works with 
rustc 1.78.0 (9b00956e5 2024-04-29)

Would help to provide diagnostics like rust and solana version

**Comment by thsioutas** [comment]
Verified that it works fine with
rustc 1.75.0 (82e1608df 2023-12-21)
(requirement for `solana-program v1.18.17`)
