### ISSUE TITLE
Provide a "Hello Solana" Seahorse program example

### ISSUE THREAD

**Issue by cdhiraj40** [solana-developers/program-examples#2]
Hey @jpcaulfi. Recently, I found out about the [Seahorse-lang](https://seahorse-lang.org/) and would love to add examples to the repository. Along with that, [Developer Experience](https://github.com/solana-developers/developer-experience/issues/32) repository motivated me even more!

Let me know, thanks!

**Comment by jpcaulfi** [comment]
Do it up! Make any seahorse examples you want. I (or someone else) may even shoot videos on them :)
