### ISSUE TITLE
create mint-1 anchor token program

### ISSUE THREAD

**Issue by Crypt0Hackers** [solana-developers/program-examples#4]
Hey @jpcaulfi I've made an example anchor program that I think can be added to mint-1 folder as there isn't anything currently there. Could you have a look at it and see if it's suitable?  https://github.com/Amaechi-Tetteh/spltoken

**Comment by jpcaulfi** [comment]
I think you're on the right track for sure, however I don't think we should have an example that uses that many unchecked accounts. Perhaps add the creation of each account to the program using Anchor's `AccountLoader::init` ?   
   
If the purpose of your example is to demonstrate creation of the Mint & ATA ahead of time on client-side, we should at least include the Account Data checks.
