### ISSUE TITLE
     Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Cross-program invocation with unauthorized signer or writable account

### ISSUE THREAD

**Issue by Ayomide57** [solana-developers/program-examples#48]
Hello there, 
Please I have this bug i have been facing, i have tried everything but it’s not working
this is the raw error message
Error: Raw transaction 4n7GkQVEtedpvjMU27nnfhwxJhXh6xHxCG7VV8taVtdhvEyo7BfEdkctX84zx3CEvxxFCYCLEbPiFPKzB9AsEuXi failed ({"err":{"InstructionError":[0,"PrivilegeEscalation"]}})

Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Cross-program invocation with unauthorized signer or writable account

Please here is my code, i will really appreciate it of anyone can help

<img width="1007" alt="Screenshot 2023-09-07 at 14 54 10" src="https://github.com/solana-developers/program-examples/assets/39005838/eb9a1d52-f1b0-434a-9f1e-386f09fee1e7">

And here is my test code below
<img width="1007" alt="Screenshot 2023-09-07 at 14 54 20" src="https://github.com/solana-developers/program-examples/assets/39005838/af5da0cf-38b7-45be-9b56-905923491c5d">
<img width="1007" alt="Screenshot 2023-09-07 at 14 54 31" src="https://github.com/solana-developers/program-examples/assets/39005838/52d253eb-15b1-44e9-b01c-d0d31cd43750">

**Comment by Woody4618** [comment]
Hey these questions are better suited for https://solana.stackexchange.com 

You are missing the payer as signer.

**Comment by Ayomide57** [comment]
Okay, please can you point to that part please

**Comment by Ayomide57** [comment]
@Woody4618  thank you i have solved the issue, i set the accountData is_writable to true instead of false.
Thank you
