### ISSUE TITLE
Why token swap  only works in devnet?

### ISSUE THREAD

**Issue by clarkchen** [solana-developers/program-examples#69]
If update the anchor.toml to localnet 

```
[programs.localnet]
swap_example = "C3ti6PFK6PoYShRFx1BNNTQU3qeY1iVwjwCA6SjJhiuW"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"


```

runing the test will fail

```
TypeError: Cannot read properties of undefined (reading 'programId')
```

why and how to modify it works in local net ?

**Comment by 19-xiaogao** [comment]
Because you need to deploy a token extension locally. In the create_token chapter, the solana program needs to interact with the extension.

**Comment by 19-xiaogao** [comment]
But I can't figure out how to deploy it.

**Comment by jafar75** [comment]
@clarkchen did you solve your issue?    Also, I have the same problem even in Devnet

**Comment by clarkchen** [comment]
@jafar75  yes, i'll close it

**Comment by kuchaguangjie** [comment]
How did you solve it.
